### ISSUE TITLE
[BA] Sheets API Mitarbeiter

### ISSUE THREAD

**Issue by LinnigLorenz** [Quickfix-Deamons-2/quickfix-deamons-2.github.io#10]
- GET: alle Evaluationsbögen laden (Bogenname, Kriterien, zugeordnete Studiengänge)
- POST: neuen Evaluationsbogen zufügen
- PUT: Evaluationsbogen bearbeiten

**Comment by sestic-fhdw** [comment]
Done Ready to Review

**Comment by sestic-fhdw** [comment]
done in master
