### ISSUE TITLE
[BA] Applications API Mitarbeiter

### ISSUE THREAD

**Issue by LinnigLorenz** [Quickfix-Deamons-2/quickfix-deamons-2.github.io#11]
- GET: alle Bewerbungen laden, einzelne Bewerbung laden
- PUT: Bewerbung bearbeiten (StudiengangID, Name, Mail, Telefonnr., Anschreiben, Dateien, Evaluationsbogen, Status)
- Evaluationsbogen je Bewerber ausfüllbar

**Comment by sestic-fhdw** [comment]
Done 
ready to Review

**Comment by sestic-fhdw** [comment]
done in master
