### ISSUE TITLE
[BA] Applications API Bewerber

### ISSUE THREAD

**Issue by LinnigLorenz** [Quickfix-Deamons-2/quickfix-deamons-2.github.io#7]
- GET: einzelne Bewerbung laden (Bewerber mit Link)
- POST: neue Bewerbung zufügen (StudiengangID, Name, Mail, Telefonnr., Anschreiben, Dateien)
- Dateiupload als PDF

**Comment by sestic-fhdw** [comment]
Done Ready to Review

**Comment by sestic-fhdw** [comment]
done in master
