### ISSUE TITLE
[BA] Courses API Mitarbeiter

### ISSUE THREAD

**Issue by LinnigLorenz** [Quickfix-Deamons-2/quickfix-deamons-2.github.io#9]
- GET: alle Studiengänge laden, einzelnen Studiengang laden (Titel, Abschlussart, Startdatum, Beschreibung, Aktiviert/Deaktiviert)
- POST: neuen Studiengang zufügen
- PUT: Studiengang bearbeiten

**Comment by sestic-fhdw** [comment]
Done in Member-Controller 
Pull Request started

**Comment by sestic-fhdw** [comment]
done in master
